import type { IJob } from "../types";

export const jobs: IJob[] = [
  {
    id: "1",
    title: "Laravel Developer",
    description:
      "We are searching for a Laravel developer to build web applications for our company. In this role, you will design and create projects using Laravel framework and PHP, and assist the team in delivering high-quality web applications, services, and tools.",
    deadLine: "12/08/2022",
    length: "2 years",
    level: "Mid level",
    location: "San Francisco, USA",
    qualification: "Bachelor",
    requirement: [
      "Degree in computer science or related field.",
      "Experience working with PHP and REST APIs.",
      "Solid understanding of Laravel and MVC.",
      "Knowledge of SQL database design.",
      "Proficiency in HTML, CSS, and JavaScript.",
    ],
    responsibilities: [
      "Develop and maintain Laravel applications.",
      "Collaborate with designers and backend developers.",
      "Optimize performance and fix bugs.",
      "Write clean and maintainable code.",
    ],
    salary: "$105,000 - 150,000",
    time: "Full Time",
  },
  {
    id: "2",
    title: "React Frontend Developer",
    description:
      "We are looking for a skilled React developer to join our front-end team and build interactive user interfaces.",
    deadLine: "20/11/2025",
    length: "Full-time",
    level: "Junior level",
    location: "Remote",
    qualification: "Bachelor or equivalent experience",
    requirement: [
      "Proficiency in JavaScript, TypeScript, and React.",
      "Understanding of state management (Redux, Zustand).",
      "Knowledge of RESTful APIs and JSON.",
      "Experience with modern CSS frameworks (Tailwind, MUI).",
    ],
    responsibilities: [
      "Develop responsive web interfaces using React.",
      "Implement reusable UI components.",
      "Collaborate with backend developers and designers.",
      "Ensure high performance and cross-browser compatibility.",
    ],
    salary: "$70,000 - 90,000",
    time: "Full Time",
  },
  {
    id: "3",
    title: "UI/UX Designer",
    description:
      "We are hiring a creative UI/UX Designer to craft user-centered digital experiences for our products.",
    deadLine: "05/01/2026",
    length: "Contract - 6 months",
    level: "Mid-Senior level",
    location: "Berlin, Germany",
    qualification: "Bachelor in Design or similar",
    requirement: [
      "Experience with Figma, Adobe XD, or Sketch.",
      "Strong understanding of design systems.",
      "Ability to prototype and test user flows.",
      "Knowledge of responsive and accessibility standards.",
    ],
    responsibilities: [
      "Create wireframes, mockups, and prototypes.",
      "Collaborate with developers to ensure correct implementation.",
      "Conduct user testing and iterate on feedback.",
      "Maintain design consistency across platforms.",
    ],
    salary: "$85,000 - 110,000",
    time: "Full Time",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    description:
      "We are seeking a DevOps Engineer to automate and streamline our deployment operations and processes.",
    deadLine: "18/12/2025",
    length: "3 years",
    level: "Senior level",
    location: "Toronto, Canada",
    qualification: "Bachelor in Computer Science or related field",
    requirement: [
      "Experience with AWS, Docker, and Kubernetes.",
      "Knowledge of CI/CD pipelines (GitHub Actions, Jenkins).",
      "Strong scripting skills (Bash, Python).",
      "Monitoring and logging using Prometheus, Grafana.",
    ],
    responsibilities: [
      "Design and manage scalable infrastructure.",
      "Automate deployment pipelines.",
      "Ensure system reliability and uptime.",
      "Collaborate with developers to optimize delivery.",
    ],
    salary: "$120,000 - 160,000",
    time: "Full Time",
  },
  {
    id: "5",
    title: "Full Stack Developer",
    description:
      "Join our engineering team as a Full Stack Developer to work on modern, scalable web applications.",
    deadLine: "15/02/2026",
    length: "Full-time",
    level: "Mid level",
    location: "Dubai, UAE",
    qualification: "Bachelor in Software Engineering",
    requirement: [
      "Strong knowledge of React and Node.js.",
      "Experience with databases (MongoDB, PostgreSQL).",
      "Understanding of REST and GraphQL APIs.",
      "Good problem-solving and debugging skills.",
    ],
    responsibilities: [
      "Develop end-to-end web solutions.",
      "Integrate APIs and handle data flow.",
      "Collaborate with design and QA teams.",
      "Maintain and refactor existing codebases.",
    ],
    salary: "$90,000 - 120,000",
    time: "Full Time",
  },
];
